version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: on-failure
    container_name: api-controle-livros
    image: api-controle-livros
    ports:
      - '3055:3055'
    volumes:
      - .:/usr/src/app
