name: CI/CD

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  pull_request:
    branches: ['dev', 'main']

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile.prod
          push: false
          tags: drakkefit/controle-livros-api:latest

  cd:
    needs: ci
    runs-on: ubuntu-latest

    if: ${{ github.event_name != 'pull_request' }}

    steps:
      - name: show version
        run: echo ${{ needs.ci.outputs.new_version }}
